<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

      	<div class="front-block block app">
	  <h3><a href="http://github.com/poulson/Clique">Clique</a></h3>
          <img alt='' src='/_static/images/clique.png'
          class='avatar avatar-84 photo' height='84' width='84' />

	  <p><a href="http://github.com/poulson/Clique">Clique</a> is a 
          distributed-memory sparse-direct solver...</p>
        </div>

      	<div class="front-block block app">
	  <h3><a href="http://github.com/poulson/PSP">PSP &mdash; Parallel Sweeping Preconditioner</a></h3>
          <img alt='' src='/_static/images/psp.png'
          class='avatar avatar-84 photo' height='84' width='84' />

	  <p><a href="http://github.com/poulson/PSP">PSP</a> is a prototype
             <a href="http://epubs.siam.org/doi/abs/10.1137/120871985">parallel
             sweeping preconditioner</a> for 
             large-scale
             heterogeneous 3D time-harmonic wave equations.
          </p>
        </div>

      	<div class="front-block block app">
	  <h3><a href="https://www.mcs.anl.gov/petsc/">PETSc &mdash; Portable, Extensible Toolkit for Scientific Computation</a></h3>
          <img alt='' src='/_static/images/petsc.jpg'
          class='avatar avatar-84 photo' height='84' width='84' />

	  <p><a href="https://www.mcs.anl.gov/petsc/">PETSc</a> is a 
             heavily-used library for solving large-scale computational science
             problems on distributed-memory machines. PETSc currently interfaces
             to Elemental for its distributed-memory dense linear algebra.
          </p>
        </div>

        <div class="front-block block app">
          <h3>Your application here?</h3>
        </div>

      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
