<div id="main">
  <div id="container" class="feature">
    <div id="content"> 
      <div id="sub-feature">

      	<div class="front-block block">
  	  <h3><a href="http://hpac.rwth-aachen.de/~pauldj/">Paolo Bientinesi</a></h3>
          <div class="avatar mugshot">
	    <img alt='Paolo Bientinesi'
		 src='/_static/images/mugshots/paolo-bientinesi.jpg' />
	  </div>

          <p>
          <a href="http://hpac.rwth-aachen.de/~pauldj/">Paolo</a>
          is a professor of computer science at 
          <a href="http://www.rwth-aachen.de/">RWTH Aachen</a> and 
          led the effort behind 
          <a href="http://arxiv.org/abs/1205.2107">Parallel Multiple Relatively Robust Representations (PMRRR)</a>, which is the 
          high-performance symmetric-tridiagonal eigensolver at the core of 
          Elemental's Hermitian eigensolver.</p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://59a2.org/research/">Jed Brown</a></h3>
          <div class="avatar mugshot">
	    <img alt='Jed Brown'
		 src='/_static/images/mugshots/jed-brown.jpg' />
	  </div>

          <p><a href="http://59a2.org/research/">Jed</a> is an 
          Assistant Computational Mathematician in the 
          <a href="https://www.mcs.anl.gov/research/LANS/">Laboratory for 
          Advanced Numerical Simulation</a> and an adjoint Assistant Prof.
          of CS at UC Boulder. He is a prolific contributor to 
          <a href="https://www.mcs.anl.gov/petsc/">PETSc</a>, helped lead the 
          development of its interface to Elemental,
          and contributed a large number of patches to Elemental along the way.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="https://github.com/rocanale">Rodrigo Canales</a></h3>
          <div class="avatar mugshot">
	    <img alt='Rodrigo Canales'
		 src='/_static/images/mugshots/rodrigo.jpg' />
	  </div>

          <p>
          <a href="https://github.com/rocanale">Rodrigo</a>
          is a Master's student in the <a href ="http://hpac.rwth-aachen.de/people/">High Performance and Automatic Computing Group</a> at RWTH Aachen and is the author of <a href="https://github.com/rocanale/R-Elemental">the R interface to Elemental</a>.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://stanford.edu/~ajfriend/">AJ Friend</a></h3>
          <div class="avatar mugshot">
	    <img alt='AJ Friend'
		 src='/_static/images/mugshots/aj-friend.jpg' />
	  </div>

          <p><a href="http://stanford.edu/~ajfriend/">AJ</a> 
          is a Ph.D. student in 
          <a href="http://web.stanford.edu/~boyd/">Stephen Boyd's</a> 
          Information Systems Laboratory at Stanford University.
          He has helped to usher in Elemental's support for convex optimization
          and wrote the original drafts of several of the ADMM routines and 
          proximal maps.
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://pcl.intel-research.net/people/jeff.htm">Jeff Hammond</a></h3>
          <div class="avatar mugshot">
	    <img alt='Jeff Hammond'
		 src='/_static/images/mugshots/jeff-hammond.jpg' />
	  </div>

          <p><a href="http://pcl.intel-research.net/people/jeff.htm">Jeff</a> 
          is a Research Scientist in the Parallel Computing Lab at Intel Labs
          and was previously an Assistant Computational Scientist at the
          <a href="https://www.alcf.anl.gov/">Argonne National 
          Laboratory Leadership Computing Facility</a>.
          He has continually helped with efforts to port/tune Elemental 
          on various machines.
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://hpac.rwth-aachen.de/~petschow/">Matthias Petschow</a></h3>
          <div class="avatar mugshot">
	    <img alt='Matthias Petschow'
		 src='/_static/images/mugshots/matthias-petschow.jpg' />
	  </div>

          <p><a href="http://hpac.rwth-aachen.de/~petschow/">Matthias</a> 
             recently completed his Ph.D. at 
             <a href="http://www.rwth-aachen.de/">RWTH Aachen</a> and is 
             interested in
             developing and applying high-performance eigensolvers to 
             large-scale quantum-mechanical problems. He co-developed
             <a href="http://arxiv.org/abs/1205.2107">PMRRR</a> 
             and <a href="http://code.google.com/p/mr3smp/">MR3-SMP</a> with
             Paolo, and the former is an integral part of Elemental's Hermitian 
             eigensolvers.</p>
        </div>
      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
