<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

      	<div class="front-block block">
  	  <h2><a href="http://hpac.rwth-aachen.de/~pauldj/">Paolo Bientinesi</a></h2>
          <div class="avatar mugshot">
	    <img alt='Paolo Bientinesi'
		 src='/_static/images/mugshots/paolo-bientinesi.jpg' />
	  </div>

          <p>
          <a href="http://hpac.rwth-aachen.de/~pauldj/">Paolo</a>
          is a professor of computer science at 
          <a href="http://www.rwth-aachen.de/">RWTH Aachen</a> and 
          led the effort behind 
          <a href="http://arxiv.org/abs/1205.2107">Parallel Multiple Relatively Robust Representations (PMRRR)</a>, which is the 
          high-performance symmetric-tridiagonal eigensolver at the core of 
          Elemental's Hermitian eigensolver.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://59a2.org/research/">Jed Brown</a></h2>
          <div class="avatar mugshot">
	    <img alt='Jed Brown'
		 src='/_static/images/mugshots/jed-brown.jpg' />
	  </div>

          <p><a href="http://59a2.org/research/">Jed</a> is currently an 
          Argonne Scholar in the 
          <a href="https://www.mcs.anl.gov/research/LANS/">Laboratory for 
          Advanced Numerical Simulation</a>. He is a prolific contributor to 
          <a href="https://www.mcs.anl.gov/petsc/">PETSc</a>, helped lead the 
          development of its interface to Elemental and 
          <a href="http://github.com/poulson/Clique">Clique</a>, 
          and contributed a large number of patches to Elemental along the way.
          He is also the lead developer of 
          <a href="https://github.com/jedbrown/dohp">dohp</a> and
          <a href="https://github.com/jedbrown/git-fat">git-fat</a>.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="https://github.com/rocanale">Rodrigo Canales</a></h2>
          <div class="avatar mugshot">
	    <img alt='Rodrigo Canales'
		 src='/_static/images/mugshots/rodrigo.jpg' />
	  </div>

          <p>
          <a href="https://github.com/rocanale">Rodrigo</a>
          is a Master's student in the <a href ="http://hpac.rwth-aachen.de/people/">High Performance and Automatic Computing Group</a> at RWTH Aachen and is the author of <a href="https://github.com/rocanale/R-Elemental">the R interface to Elemental</a>.
          </p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://pcl.intel-research.net/people/jeff.htm">Jeff Hammond</a></h2>
          <div class="avatar mugshot">
	    <img alt='Jeff Hammond'
		 src='/_static/images/mugshots/jeff-hammond.jpg' />
	  </div>

          <p><a href="http://pcl.intel-research.net/people/jeff.htm">Jeff</a> 
          is a Research Scientist in the Parallel Computing Lab at Intel Labs
          and was previously an Assistant Computational Scientist at the
          <a href="https://www.alcf.anl.gov/">Argonne National 
          Laboratory Leadership Computing Facility</a>.
          He has continually helped with efforts to port and tune Elemental 
          on various supercomputers, including <a href="https://en.wikipedia.org/wiki/Blue_Gene#Blue_Gene.2FP">Blue Gene/P</a>, <a href="https://en.wikipedia.org/wiki/Blue_Gene#Blue_Gene.2FQ">Blue Gene/Q</a>, and 
          <a href="http://www.cray.com/Products/Computing/XE.aspx">Cray XE6</a> 
          systems.
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://hpac.rwth-aachen.de/~petschow/">Matthias Petschow</a></h2>
          <div class="avatar mugshot">
	    <img alt='Matthias Petschow'
		 src='/_static/images/mugshots/matthias-petschow.jpg' />
	  </div>

          <p><a href="http://hpac.rwth-aachen.de/~petschow/">Matthias</a> 
             is a Ph.D. student at 
             <a href="http://www.rwth-aachen.de/">RWTH Aachen</a> interested in
             developing and applying high-performance eigensolvers to 
             large-scale quantum-mechanical problems. He is one of the lead 
             developers of <a href="http://arxiv.org/abs/1205.2107">PMRRR</a>
             and <a href="http://code.google.com/p/mr3smp/">MR3-SMP</a>, and the
             former is an integral part of Elemental's Hermitian 
             eigensolvers.</p>
        </div>
      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
