<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">
      	<div class="front-block block">
  	  <h2><a href="http://www.stanford.edu/~poulson">Jack Poulson</a></h2>
          <div class="avatar mugshot">
	    <img alt='Jack Poulson'
		 src='/_static/images/mugshots/jack-poulson.jpg' />
	  </div>
          <p>
          Jack is an Assistant Prof. in 
          <a href="http://mathematics.stanford.edu">Stanford's Dept. of Mathematics</a>
          and a Member of the <a href="http://icme.stanford.edu">Inst. for Computational and Mathematical 
          Eng.</a>. He was previously an 
          <a href="http://www.cse.gatech.edu/">Assistant Prof. at Georgia Tech</a> and is
          a graduate of UT Austin's <a href="http://www.ices.utexas.edu">Inst. for Computational Engineering and
          Sciences</a>.
          </p>
          <p>He has led the development of Elemental since its start in 2009,
             as well as that of
             <a href="http://www.github.com/poulson/dist-butterfly">DistButterfly</a> and <a href="http://github.com/poulson/rt-lps-mri">Low-rank Plus Sparse MRI</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
