<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">
      	<div class="front-block block">
  	  <h2><a href="http://www.github.com/poulson">Jack Poulson</a></h2>
          <div class="avatar mugshot">
	    <img alt='Jack Poulson'
		 src='/_static/images/mugshots/jack-poulson.jpg' />
	  </div>
          <p>
          Jack was recently affiliated with the Georgia Institute of Technology 
          but has recently accepted a Simon's Math+X joint tenure-track 
          position in Stanford's Math department and Institute for 
          Computational and Mathematical Engineering (ICME).
          </p>
          <p>He has led the development of Elemental since its start in 2009,
             as well as that of
             <a href="http://www.github.com/poulson/Clique">a sparse-direct solver</a>, 
             <a href="http://www.github.com/poulson/dist-butterfly">butterfly algorithms</a>, and <a href="http://github.com/poulson/rt-lps-mri">Low-rank Plus Sparse MRI</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
