<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">
      	<div class="front-block block">
  	  <h2><a href="http://www.cc.gatech.edu/~jpoulson">Jack Poulson</a></h2>
          <div class="avatar mugshot">
	    <img alt='Jack Poulson'
		 src='/_static/images/mugshots/jack-poulson.jpeg' />
	  </div>
	  <p><a href="http://www.cc.gatech.edu/~jpoulson">Jack</a> is an 
          Assistant Professor of Computational Science and Engineering at 
          <a href="http://www.cse.gatech.edu/">The Georgia Institute of 
          Technology</a>.
          </p>
          <p>He has led the development of Elemental since its start in 2009,
             as well as that of
             <a href="http://www.github.com/poulson/Clique.git">a distributed sparse-direct solver</a>, 
             <a href="http://www.github.com/poulson/dist-butterfly.git">a distributed butterfly algorithm</a>, and <a href="http://bitbucket.org/poulson/dmhm">distributed hierarchical matrices</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
