<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

        <div class="front-block block">
          <h3><a href="http://59a2.org/research/">Jed Brown</a></h3>
          <div class="avatar mugshot">
            <img alt='Jed Brown'
                 src='/_static/images/mugshots/jed-brown.jpg' />
          </div>

          <p>
          <a href="http://59a2.org/research/">Jed</a> is an
          Assistant Computational Mathematician in the
          <a href="https://www.mcs.anl.gov/research/LANS/">Laboratory for
          Advanced Numerical Simulation</a> and an adjoint Assistant Prof.
          of CS at UC Boulder. He is a prolific contributor to
          <a href="https://www.mcs.anl.gov/petsc/">PETSc</a>, helped lead the
          development of its interface to Elemental,
          and contributed a large number of patches to Elemental along the way.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://cvxr.com/bio/">Michael Grant</a></h3>
          <div class="avatar mugshot">
	    <img alt='Michael Grant'
		 src='/_static/images/mugshots/michael-grant.png' />
	  </div>

          <p>
          <a href="http://cvxr.com/bio/">Michael</a> is a computational 
          mathematician and co-founded (along with <a href="http://stanford.edu/~boyd/">Stephen Boyd</a>) <a href="http://cvxr.com">CVX Research</a>, which 
          produced the <a href="http://mathopt.org/?nav=boh">award-winning</a> 
          <a href="http://cvxr.com/cvx/">CVX</a> and 
          <a href="http://cvxr.com/tfocs/">TFOCS</a> libraries. 
          Michael was the lead developer behind Elemental's initial
          Python interface (via <a href="http://www.swig.org/">.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://www.mit.edu/~mlubin/">Miles Lubin</a></h3>
          <div class="avatar mugshot">
	    <img alt='Miles Lubin'
		 src='/_static/images/mugshots/miles-lubin.jpeg' />
	  </div>

          <p>
          <a href="http://www.mit.edu/~mlubin/">Miles</a> is a 
          Ph.D. student in 
          <a href="http://www.mit.edu/~orc/">Operations Research at MIT</a>.
          His interests include high-performance optimization and probability
          and statistics, and he is associated with the 
          <a href="http://julialang.org/">Julia project</a> (see 
          <a href="https://github.com/IainNZ/MathProg.jl">MathProg.jl</a>).
          He was one of the early users of Elemental (in 2009) and contributed
          numerous bug reports and suggestions.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://www.cs.utexas.edu/~bamarker/">Bryan Marker</a></h3>
          <div class="avatar mugshot">
	    <img alt='Bryan Marker'
		 src='/_static/images/mugshots/bryan-marker.png' />
	  </div>

          <p>
          <a href="http://www.cs.utexas.edu/~bamarker/">Bryan</a> is a 
          Postdoctoral Researcher at 
          <a href="http://www.utexas.edu">UT Austin</a> 
          interested in bridging the gap between library developers and 
          compilers. He has contributed a large number of improvements to 
          Elemental's BLAS-like routines using automatic program generation via
          <a href="https://code.google.com/p/dxter/">DxTer</a>.</p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://www.opt.mist.i.u-tokyo.ac.jp/~nakatsukasa/">Yuji Nakatsukasa</a></h3>
          <div class="avatar mugshot">
	    <img alt='Yuji Nakatsukasa'
		 src='/_static/images/mugshots/yuji-nakatsukasa.jpg' />
	  </div>

          <p>
          <a href="http://www.opt.mist.i.u-tokyo.ac.jp/~nakatsukasa/">Yuji</a> 
          is an assistant professor in the 
          <a href="http://www.opt.mist.i.u-tokyo.ac.jp/">Operations Research group</a> at 
          <a href="http://www.u-tokyo.ac.jp/en/">The University of Tokyo</a>.
          His research focuses on algorithms and perturbation theory for 
          eigenvalue problems, and his implementation of <a href="http://www.mathworks.com/matlabcentral/fileexchange/36830">QDWH</a> served as the basis for Elemental's implementation.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://www3.uji.es/~gquintan/">Gregorio Quintana Orti</a></h3>
          <!---
          <div class="avatar mugshot">
	    <img alt='Gregorio Quintana Orti'
		 src='/_static/images/mugshots/gregorio-quintana.jpg' />
	  </div>
          ---!>

          <p>
          <a href="http://www3.uji.es/~gquintan/">Gregorio</a> is a professor
          of computer science at 
          <a href="http://ujiapps.uji.es/">Universitat Jaume-I</a> and has 
          extensive experience with parallel algorithms for rank-revealing 
          factorizations and control theory. He contributed to Elemental's 
          implementation of QDWH and helped with the process of wrapping 
          libflame's bidiaogonal QR algorithm.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="https://www.alcf.anl.gov/staff-directory/nichols-romero">Nichols Romero</a></h3>
          <div class="avatar mugshot">
	    <img alt='Nichols Romero'
		 src='/_static/images/mugshots/nichols-romero.jpg' />
	  </div>

          <p>
          <a href="https://www.alcf.anl.gov/staff-directory/nichols-romero">Nick</a> 
          is an Assistant Computational Scientist at the 
          <a href="https://www.alcf.anl.gov/">Argonne Leadership Computing 
          Facility</a> and received his Ph.D. from 
          <a href="http://illinois.edu/">UIUC</a> in 2005. His primary focus is
          massively parallel electronic structure calculations and he is a 
          contributor to <a href="https://wiki.fysik.dtu.dk/gpaw/">GPAW</a>. 
          He helped support Elemental's port to Blue Gene/P.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3>Martin Schatz</h3>
          <!---
          <div class="avatar mugshot">
	    <img alt='Martin Schatz'
		 src='/_static/images/mugshots/martin-schatz.jpg' />
	  </div>
          ---!>

          <p>
          Martin is a Ph.D. student at 
          <a href="http://www.utexas.edu">UT Austin</a> interested in the 
          development and application of high-performance algorithms and 
          libraries for tensor contractions. He is the author of both the 
          "Axpy interface" and the experimental 3D Gemm implementation</a>.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://folk.uio.no/dagss">Dag Sverre Seljebotn</a></h3>
          <div class="avatar mugshot">
	    <img alt='Dag Sverre Seljebotn'
		 src='/_static/images/mugshots/dag-seljebotn.jpeg' />
	  </div>

          <p>
          <a href="http://folk.uio.no/dagss">Dag</a> is a doctoral student
          in the <a href="http://www.mn.uio.no/astro/">Institute of Theoretical
          Astrophysics</a> at
          <a href="https://www.uio.no/english/">The University of Oslo</a> 
          analyzing the
          <a href="https://en.wikipedia.org/wiki/Cosmic_microwave_background_radiation">cosmic microwave background</a>.
          He is one of the core developers of 
          <a href="http://cython.org/">Cython</a> and 
          <a href="http://fwrap.sourceforge.net/">Fwrap</a> and was the first to
          work towards a Python interface to Elemental (see 
          <a href="https://github.com/dagss/elemental4py">elemental4py</a>).
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://andy.terrel.us">Andy Terrel</a></h3>
          <div class="avatar mugshot">
	    <img alt='Andy Terrel'
		 src='/_static/images/mugshots/andy-terrel.jpeg' />
	  </div>

          <p>
          <a href="http://andy.terrel.us">Andy Terrel</a> is the
          Chief Science Officer for <a href="http://continuum.io/our-team/index">Continuum Analytics</a> and recieved his PhD in Computer Science from 
          <a href="http://www.uchicago.edu">The University of 
          Chicago</a> in  2010. He helped provide very early advice on various
          approached to a Python interface to Elemental.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://www.cs.utexas.edu/~rvdg/">Robert van de Geijn</a></h3>
          <div class="avatar mugshot">
	    <img alt='Robert van de Geijn'
		 src='/_static/images/mugshots/robert-vdg.jpg' />
	  </div>

          <p>
          <a href="http://www.cs.utexas.edu/~rvdg/">Robert</a> is a professor
          of computer science at <a href="http://www.utexas.edu">UT Austin</a>
          and has helped support Elemental since its inception. He is currently
          leading the research and development of 
          <a href="http://www.cs.utexas.edu/~flame/web/libFLAME.html">libflame</a> and <a href="https://code.google.com/p/blis/">BLIS</a> and previously 
          led the development of 
          <a href="http://www.cs.utexas.edu/~plapack">PLAPACK</a>, which was 
          the primary inspiration for Elemental.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://www.cs.utexas.edu/~field/">Field Van Zee</a></h3>
          <div class="avatar mugshot">
	    <img alt='Field Van Zee'
		 src='/_static/images/mugshots/field-vanzee.jpg' />
	  </div>

          <p>
          <a href="http://www.cs.utexas.edu/~field/">Field</a> is a Research
          Scientist Associate III at 
          <a href="http://www.utexas.edu">UT Austin</a> and is the lead
          developer of 
          <a href="http://www.cs.utexas.edu/~flame/web/libFLAME.html">libflame</a>
          and <a href="https://code.google.com/p/blis/">BLIS</a>. He helped 
          support the usage of libflame's high-performance bidiagonal
          QR algorithm within Elemental's parallel SVD.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3><a href="http://www.mcs.anl.gov/~hzhang">Hong Zhang</a></h3>
          <div class="avatar mugshot">
	    <img alt='Hong Zhang'
		 src='/_static/images/mugshots/hong-zhang.jpg' />
	  </div>

          <p>
          <a href="https://www.mcs.anl.gov/~hzhang">Hong</a> is a research 
          professor of computer science at <a href="http://www.iit.edu/">IIT</a>
          and is affiliated with the 
          <a href="http://www.mcs.anl.gov/">MCS division</a> of 
          <a href="http://www.anl.gov/">Argonne National Laboratory</a>.
          Hong helped lead the development of 
          <a href="https://www.mcs.anl.gov/petsc/">PETSc's</a> interface to 
          Elemental and <a href="http://github.com/poulson/Clique">Clique</a>.
          </p>
        </div>

      	<div class="front-block block">
  	  <h3>Xuan Zhou</h3>
          <div class="avatar mugshot">
	    <img alt='Xuan Zhou'
		 src='/_static/images/mugshots/xuan-zhou.jpg' />
	  </div>

          <p>
          Xuan is a Ph.D. candidate in applied mathematics at 
          <a href="http://www.iit.edu/">IIT</a> and helped develop 
          <a href="https://www.mcs.anl.gov/petsc/">PETSc's</a> interface to 
          Elemental and <a href="http://github.com/poulson/Clique">Clique</a>.
          </p>
        </div>
      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
