<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

      	<div class="front-block block">
  	  <h2><a href="http://hpac.rwth-aachen.de/~pauldj/">Paolo Bientinesi</a></h2>
          <div class="avatar mugshot">
	    <img alt='Paolo Bientinesi'
		 src='/_static/images/mugshots/paolo-bientinesi.jpg' />
	  </div>

          <p>
          <a href="http://hpac.rwth-aachen.de/~pauldj/">Paolo</a>
          is a professor of computer science at 
          <a href="http://www.rwth-aachen.de/">RWTH Aachen</a> and 
          led the effort behind 
          <a href="http://arxiv.org/abs/1205.2107">Parallel Multiple Relatively Robust Representations (PMRRR)</a>, which is the 
          high-performance symmetric-tridiagonal eigensolver at the core of 
          Elemental's Hermitian eigensolver.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://59a2.org/research/">Jed Brown</a></h2>
          <div class="avatar mugshot">
	    <img alt='Jed Brown'
		 src='/_static/images/mugshots/jed-brown.jpg' />
	  </div>

          <p><a href="http://59a2.org/research/">Jed</a> is currently an 
          Argonne Scholar in the 
          <a href="https://www.mcs.anl.gov/research/LANS/">Laboratory for 
          Advanced Numerical Simulation</a>. He is a prolific contributor to 
          <a href="https://www.mcs.anl.gov/petsc/">PETSc</a>, helped lead the 
          development of its interface to Elemental and 
          <a href="http://github.com/poulson/Clique">Clique</a>, 
          and contributed a large number of patches to Elemental along the way.
          He is also the lead developer of 
          <a href="https://github.com/jedbrown/dohp">dohp</a> and
          <a href="https://github.com/jedbrown/git-fat">git-fat</a>.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://cvxr.com/bio/">Michael Grant</a></h2>
          <div class="avatar mugshot">
	    <img alt='Michael Grant'
		 src='/_static/images/mugshots/michael-grant.png' />
	  </div>

          <p><a href="http://cvxr.com/bio/">Michael</a> is a computational 
          mathematician and co-founded (along with <a href="http://stanford.edu/~boyd/">Stephen Boyd</a>) <a href="http://cvxr.com">CVX Research</a>, which 
          produced the <a href="http://mathopt.org/?nav=boh">award-winning</a> 
          <a href="http://cvxr.com/cvx/">CVX</a> and 
          <a href="http://cvxr.com/tfocs/">TFOCS</a> libraries. 
          Michael is the lead developer behind Elemental's 
          <a href="http://www.swig.org/">SWIG</a> Python interface.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="https://wiki.alcf.anl.gov/parts/index.php/User:Jhammond">Jeff Hammond</a></h2>
          <div class="avatar mugshot">
	    <img alt='Jeff Hammond'
		 src='/_static/images/mugshots/jeff-hammond.jpg' />
	  </div>

          <p><a href="https://wiki.alcf.anl.gov/parts/index.php/User:Jhammond">Jeff</a> 
          is an Assistant Computational Scientist at the 
          <a href="https://www.alcf.anl.gov/">Argonne National 
          Laboratory Leadership Computing Facility</a>, where he works to 
          develop scalable algorithms and robust software for computational 
          chemistry and PGAS programming models.  
          He has continually helped with efforts to port and tune Elemental 
          on various supercomputers, including <a href="https://en.wikipedia.org/wiki/Blue_Gene#Blue_Gene.2FP">Blue Gene/P</a>, <a href="https://en.wikipedia.org/wiki/Blue_Gene#Blue_Gene.2FQ">Blue Gene/Q</a>, and 
          <a href="http://www.cray.com/Products/Computing/XE.aspx">Cray XE6</a> 
          systems.
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.mit.edu/~mlubin/">Miles Lubin</a></h2>
          <div class="avatar mugshot">
	    <img alt='Miles Lubin'
		 src='/_static/images/mugshots/miles-lubin.jpeg' />
	  </div>

          <p><a href="http://www.mit.edu/~mlubin/">Miles</a> is a 
          Ph.D. student in 
          <a href="http://www.mit.edu/~orc/">Operations Research at MIT</a>.
          His interests include high-performance optimization and probability
          and statistics, and he is associated with the 
          <a href="http://julialang.org/">Julia project</a> (see 
          <a href="https://github.com/IainNZ/MathProg.jl">MathProg.jl</a>).
          He was one of the early users of Elemental (in 2009) and contributed
          numerous bug reports and suggestions.
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.cs.utexas.edu/~bamarker/">Bryan Marker</a></h2>
          <div class="avatar mugshot">
	    <img alt='Bryan Marker'
		 src='/_static/images/mugshots/bryan-marker.png' />
	  </div>

          <p><a href="http://www.cs.utexas.edu/~bamarker/">Bryan</a> is a 
          Ph.D. candidate at <a href="http://www.utexas.edu">UT Austin</a> 
          interested in bridging the gap between library developers and 
          compilers. He has contributed a large number of improvements to 
          Elemental's BLAS-like routines using automatic program generation via
          <a href="https://code.google.com/p/dxter/">DxTer</a>.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.opt.mist.i.u-tokyo.ac.jp/~nakatsukasa/">Yuji Nakatsukasa</a></h2>
          <div class="avatar mugshot">
	    <img alt='Yuji Nakatsukasa'
		 src='/_static/images/mugshots/yuji-nakatsukasa.jpg' />
	  </div>

          <p><a href="http://www.opt.mist.i.u-tokyo.ac.jp/~nakatsukasa/">Yuji</a> 
          is an assistant professor in the 
          <a href="http://www.opt.mist.i.u-tokyo.ac.jp/">Operations Research group</a> at 
          <a href="http://www.u-tokyo.ac.jp/en/">The University of Tokyo</a>.
          His research focuses on algorithms and perturbation theory for 
          eigenvalue problems, and his implementation of <a href="http://www.mathworks.com/matlabcentral/fileexchange/36830">QDWH</a> served as the basis for Elemental's implementation.
          </p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://hpac.rwth-aachen.de/~petschow/">Matthias Petschow</a></h2>
          <div class="avatar mugshot">
	    <img alt='Matthias Petschow'
		 src='/_static/images/mugshots/matthias-petschow.jpg' />
	  </div>

          <p><a href="http://hpac.rwth-aachen.de/~petschow/">Matthias</a> 
             is a Ph.D. student at 
             <a href="http://www.rwth-aachen.de/">RWTH Aachen</a> interested in
             developing and applying high-performance eigensolvers to 
             large-scale quantum-mechanical problems. He is one of the lead 
             developers of <a href="http://arxiv.org/abs/1205.2107">PMRRR</a>
             and <a href="http://code.google.com/p/mr3smp/">MR3-SMP</a>, and the
             former is an integral part of Elemental's Hermitian 
             eigensolvers.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www3.uji.es/~gquintan/">Gregorio Quintana Orti</a></h2>
          <!---
          <div class="avatar mugshot">
	    <img alt='Gregorio Quintana Orti'
		 src='/_static/images/mugshots/gregorio-quintana.jpg' />
	  </div>
          ---!>

          <p><a href="http://www3.uji.es/~gquintan/">Gregorio</a> is a professor
          of computer science at 
          <a href="http://ujiapps.uji.es/">Universitat Jaume-I</a> and has 
          extensive experience with parallel algorithms for rank-revealing 
          factorizations and control theory. He contributed to Elemental's 
          implementation of QDWH and helped with the process of wrapping 
          libflame's bidiaogonal QR algorithm.
          </p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="https://www.alcf.anl.gov/staff-directory/nichols-romero">Nichols Romero</a></h2>
          <div class="avatar mugshot">
	    <img alt='Nichols Romero'
		 src='/_static/images/mugshots/nichols-romero.jpg' />
	  </div>

          <p><a href="https://www.alcf.anl.gov/staff-directory/nichols-romero">Nick</a> is an Assistant Computational Scientist at the 
          <a href="https://www.alcf.anl.gov/">Argonne Leadership Computing 
          Facility</a> and received his Ph.D. from <a href="http://illinois.edu/">UIUC</a> in 2005. His primary focus is massively parallel electronic structure
          calculations and he is a contributor to 
          <a href="https://wiki.fysik.dtu.dk/gpaw/">GPAW</a>. 
          He helped support Elemental's port to Blue Gene/P.
          </p>
        </div>

      	<div class="front-block block">
  	  <h2>Martin Schatz</h2>
          <!---
          <div class="avatar mugshot">
	    <img alt='Martin Schatz'
		 src='/_static/images/mugshots/martin-schatz.jpg' />
	  </div>
          ---!>

          <p>Martin is a Ph.D. student at 
          <a href="http://www.utexas.edu">UT Austin</a> interested in the 
          development and application of high-performance algorithms and 
          libraries for tensor contractions. He is the author of both the 
          "Axpy interface" and the experimental 3D Gemm implementation</a>.
          </p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://folk.uio.no/dagss">Dag Sverre Seljebotn</a></h2>
          <div class="avatar mugshot">
	    <img alt='Dag Sverre Seljebotn'
		 src='/_static/images/mugshots/dag-seljebotn.jpeg' />
	  </div>

          <p><a href="http://folk.uio.no/dagss">Dag</a> is a doctoral student
          in the <a href="http://www.mn.uio.no/astro/">Institute of Theoretical
          Astrophysics</a> at
          <a href="https://www.uio.no/english/">The University of Oslo</a> 
          analyzing the
          <a href="https://en.wikipedia.org/wiki/Cosmic_microwave_background_radiation">cosmic microwave background</a>.
          He is one of the core developers of <a href="http://cython.org/">Cython</a> and <a href="http://fwrap.sourceforge.net/">Fwrap</a> and was the first to
          work towards a Python interface to Elemental (see <a href="https://github.com/dagss/elemental4py">elemental4py</a>).
          </p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://andy.terrel.us">Andy Terrel</a></h2>
          <div class="avatar mugshot">
	    <img alt='Andy Terrel'
		 src='/_static/images/mugshots/andy-terrel.jpeg' />
	  </div>

          <p><a href="http://andy.terrel.us">Dr. Andy R. Terrel</a> is a 
          Research Associate for the <a href="http://chg.ices.utexas.edu/index.html">Computational Hydraulics Group</a> at the 
          <a href="http://www.ices.utexas.edu">Institute for Computational 
          Engineering and Sciences</a> which is at 
          <a href="http://www.utexas.edu">The Universiy of Texas at Austin</a>. 
          Andy's research includes utilizing supercomputers with Python and 
          studying methods for speeding up computational fluid dynamics. He 
          graduated from <a href="http://www.uchicago.edu">The University of 
          Chicago</a> with a PhD in Computer Science in 2010.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.cs.utexas.edu/~rvdg/">Robert van de Geijn</a></h2>
          <div class="avatar mugshot">
	    <img alt='Robert van de Geijn'
		 src='/_static/images/mugshots/robert-vdg.jpg' />
	  </div>

          <p><a href="http://www.cs.utexas.edu/~rvdg/">Robert</a> is a professor
          of computer science at <a href="http://www.utexas.edu">UT Austin</a>
          and has helped support Elemental since its inception. He is currently
          leading the research and development of 
          <a href="http://www.cs.utexas.edu/~flame/web/libFLAME.html">libflame</a> and <a href="https://code.google.com/p/blis/">BLIS</a> and previously 
          led the development of 
          <a href="http://www.cs.utexas.edu/~plapack">PLAPACK</a>, which was 
          the primary inspiration for Elemental.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.cs.utexas.edu/~field/">Field Van Zee</a></h2>
          <div class="avatar mugshot">
	    <img alt='Field Van Zee'
		 src='/_static/images/mugshots/field-vanzee.jpg' />
	  </div>

          <p><a href="http://www.cs.utexas.edu/~field/">Field</a> is a Research
          Scientist Associate III at 
          <a href="http://www.utexas.edu">UT Austin</a> and is the lead
          developer of 
          <a href="http://www.cs.utexas.edu/~flame/web/libFLAME.html">libflame</a>
          and <a href="https://code.google.com/p/blis/">BLIS</a>. He helped 
          support the usage of libflame's high-performance bidiagonal
          QR algorithm within Elemental's parallel SVD.
          </p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.mcs.anl.gov/~hzhang">Hong Zhang</a></h2>
          <div class="avatar mugshot">
	    <img alt='Hong Zhang'
		 src='/_static/images/mugshots/hong-zhang.jpg' />
	  </div>

          <p><a href="https://www.mcs.anl.gov/~hzhang">Hong</a> is a research 
          professor of computer science at <a href="http://www.iit.edu/">IIT</a> and is affiliated with the <a href="http://www.mcs.anl.gov/">MCS division</a> of <a href="http://www.anl.gov/">Argonne National Laboratory</a>.
          Hong helped lead the development of <a href="https://www.mcs.anl.gov/petsc/">PETSc's</a> interface to Elemental and <a href="http://github.com/poulson/Clique">Clique</a>.
        </div>

      	<div class="front-block block">
  	  <h2>Xuan Zhou</h2>
          <div class="avatar mugshot">
	    <img alt='Xuan Zhou'
		 src='/_static/images/mugshots/xuan-zhou.jpg' />
	  </div>

          <p>Xuan is a Ph.D. candidate in applied mathematics at 
          <a href="http://www.iit.edu/">IIT</a> and helped develop 
          <a href="https://www.mcs.anl.gov/petsc/">PETSc's</a> interface to Elemental and <a href="http://github.com/poulson/Clique">Clique</a>.
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.libelemental.org/contributing/">Your name here?</a></h2>
          <div class="avatar mugshot">
	  </div>

        </div>

      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
