<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

      	<div class="front-block block">
  	  <h2><a href="http://hpac.rwth-aachen.de/~pauldj/">Paolo Bientinesi</a></h2>
          <div class="avatar mugshot">
	    <img alt='Paolo Bientinesi'
		 src='/_static/images/mugshots/paolo-bientinesi.jpg' />
	  </div>

          <p>
          <a href="http://hpac.rwth-aachen.de/~pauldj/">Paolo</a>
          is a professor of computer science at 
          <a href="http://www.rwth-aachen.de/">RWTH Aachen</a> and 
          led the effort behind 
          <a href="http://arxiv.org/abs/1205.2107">Parallel Multiple Relatively Robust Representations (PMRRR)</a>, which is the 
          high-performance symmetric-tridiagonal eigensolver at the core of 
          Elemental's Hermitian eigensolver.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://59a2.org/research/">Jed Brown</a></h2>
          <div class="avatar mugshot">
	    <img alt='Jed Brown'
		 src='/_static/images/mugshots/jed-brown.jpg' />
	  </div>

          <p><a href="http://59a2.org/research/">Jed</a> is currently an 
          Argonne Scholar in the 
          <a href="https://www.mcs.anl.gov/research/LANS/">Laboratory for 
          Advanced Numerical Simulation</a>. He is a prolific contributor to 
          <a href="https://www.mcs.anl.gov/petsc/">PETSc</a>, led the 
          development of its interface to Elemental and 
          <a href="http://github.com/poulson/Clique">Clique</a>, 
          and contributed a large number of patches to Elemental along the way.
          He is also the lead developer of 
          <a href="https://github.com/jedbrown/dohp">dohp</a> and
          <a href="https://github.com/jedbrown/git-fat">git-fat</a>.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://cvxr.com/bio/">Michael Grant</a></h2>
          <div class="avatar mugshot">
	    <img alt='Michael Grant'
		 src='/_static/images/mugshots/michael-grant.png' />
	  </div>

          <p><a href="http://cvxr.com/bio/">Michael</a> is a computational 
          mathematician and co-founded (along with <a href="http://stanford.edu/~boyd/">Stephen Boyd</a>) <a href="http://cvxr.com">CVX Research</a>, which 
          produced the <a href="http://mathopt.org/?nav=boh">award-winning</a> 
          <a href="http://cvxr.com/cvx/">CVX</a> and 
          <a href="http://cvxr.com/tfocs/">TFOCS</a> libraries. 
          Michael is the lead developer behind Elemental's 
          <a href="http://www.swig.org/">SWIG</a> Python interface.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="https://wiki.alcf.anl.gov/parts/index.php/User:Jhammond">Jeff Hammond</a></h2>
          <div class="avatar mugshot">
	    <img alt='Jeff Hammond'
		 src='/_static/images/mugshots/jeff-hammond.jpg' />
	  </div>

          <p><a href="https://wiki.alcf.anl.gov/parts/index.php/User:Jhammond">Jeff</a> 
          is an Assistant Computational Scientist at the 
          <a href="https://www.alcf.anl.gov/">Argonne National 
          Laboratory Leadership Computing Facility</a>, where he works to 
          develop scalable algorithms and robust software for computational 
          chemistry and PGAS programming models.  
          He has continually helped with efforts to port and tune Elemental 
          on various supercomputers, including <a href="https://en.wikipedia.org/wiki/Blue_Gene#Blue_Gene.2FP">Blue Gene/P</a>, <a href="https://en.wikipedia.org/wiki/Blue_Gene#Blue_Gene.2FQ">Blue Gene/Q</a>, and 
          <a href="http://www.cray.com/Products/Computing/XE.aspx">Cray XE6</a> 
          systems.
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.cs.utexas.edu/~bamarker/">Bryan Marker</a></h2>
          <div class="avatar mugshot">
	    <img alt='Bryan Marker'
		 src='/_static/images/mugshots/bryan-marker.png' />
	  </div>

          <p><a href="http://www.cs.utexas.edu/~bamarker/">Bryan</a> is a 
          Ph.D. candidate at <a href="http://www.utexas.edu">UT Austin</a> 
          interested in bridging the gap between library developers and 
          compilers. He has contributed a large number of improvements to 
          Elemental's BLAS-like routines using 
          <a href="https://code.google.com/p/dxter/">DxTer</a>.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://hpac.rwth-aachen.de/~petschow/">Matthias Petschow</a></h2>
          <div class="avatar mugshot">
	    <img alt='Matthias Petschow'
		 src='/_static/images/mugshots/matthias-petschow.jpg' />
	  </div>

          <p><a href="http://hpac.rwth-aachen.de/~petschow/">Matthias</a> 
             is a Ph.D. student at 
             <a href="http://www.rwth-aachen.de/">RWTH Aachen</a> interested in
             developing and applying high-performance eigensolvers to 
             large-scale quantum-mechanical problems. He is one of the lead 
             developers of <a href="http://arxiv.org/abs/1205.2107">PMRRR</a>
             and <a href="http://code.google.com/p/mr3smp/">MR3-SMP</a>, and the
             former is an integral part of Elemental's Hermitian 
             eigensolvers.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.stanford.edu/~poulson">Jack Poulson</a></h2>
          <div class="avatar mugshot">
	    <img alt='Jack Poulson'
		 src='/_static/images/mugshots/jack-poulson.jpeg' />
	  </div>

	  <p><a href="http://www.stanford.edu/~poulson">Jack</a> is a 
          postdoctoral fellow at <a href="http://www.stanford.edu/">Stanford</a>
          and will be joining <a href="http://www.cse.gatech.edu">Georgia Tech's School of CS&amp;E</a> in November. 
          </p>

          <p>He has led the development of Elemental since its start in 2009,
             as well as that of
             <a href="http://www.github.com/poulson/Clique.git">a distributed sparse-direct solver</a>, 
             <a href="http://www.github.com/poulson/dist-butterfly.git">a distributed butterfly algorithm</a>, and <a href="http://bitbucket.org/poulson/dmhm">distributed hierarchical matrices</a>.
          </p>
        </div>

      	<div class="front-block block">
  	  <h2>Martin Schatz</h2>
          <div class="avatar mugshot">
	    <img alt='Martin Schatz'
		 src='/_static/images/mugshots/martin-schatz.jpg' />
	  </div>

          <p>Martin is a Ph.D. student at 
          <a href="http://www.utexas.edu">UT Austin</a> interested in the 
          development and application of high-performance algorithms and 
          libraries for tensor contractions. He is the author of both the 
          <a href="http://poulson.github.io/Elemental/core/axpy_interface.html">Axpy interface</a> and the <a href="https://github.com/poulson/Elemental/blob/master/experimental/g3d/G3DGemm.cpp">experimental 3D Gemm implementation</a>.
          </p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.cs.utexas.edu/~rvdg/">Robert van de Geijn</a></h2>
          <div class="avatar mugshot">
	    <img alt='Robert van de Geijn'
		 src='/_static/images/mugshots/robert-vdg.jpg' />
	  </div>

          <p><a href="http://www.cs.utexas.edu/~rvdg/">Robert</a> is a professor
          of computer science at <a href="http://www.utexas.edu">UT Austin</a>
          and has helped support Elemental since its inception. He is currently
          leading the research and development of 
          <a href="http://www.cs.utexas.edu/~flame/web/libFLAME.html">libFLAME</a> and <a href="https://code.google.com/p/blis/">BLIS</a> and previously 
          led the development of 
          <a href="http://www.cs.utexas.edu/~plapack">PLAPACK</a>, which was 
          the primary inspiration for Elemental.</p>
        </div>

      	<div class="front-block block">
  	  <h2><a href="http://www.libelemental.org/contributing/">Your name here?</a></h2>
          <div class="avatar mugshot">
	  </div>

        </div>

      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
