<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

        <div class="front-block block app">
          <h3><a href="http://www.csm.ornl.gov/ccsg/html/projects/madness.html">MADNESS &mdash; Multiresolution ADaptive NumErical Scientific Simulation</a></h3>
          <img alt='' src='/_static/images/madness.jpeg'
          class='avatar avatar-84 photo' height='84' width='84' />

          <p><a href="http://www.csm.ornl.gov/ccsg/html/projects/madness.html">Madness</a> 
             is a framework for scientific simulation in many dimensions
             using adaptive multiresolution methods in multiwavelet bases.
          </p>
        </div>

      	<div class="front-block block app">
	  <h3><a href="https://www.mcs.anl.gov/petsc/">PETSc &mdash; Portable, Extensible Toolkit for Scientific Computation</a></h3>
          <img alt='' src='/_static/images/petsc.jpg'
          class='avatar avatar-84 photo' height='84' width='84' />

	  <p><a href="https://www.mcs.anl.gov/petsc/">PETSc</a> is a 
             heavily-used library for solving large-scale computational science
             problems on distributed-memory machines. PETSc currently interfaces
             to Elemental for its distributed-memory dense linear algebra.
          </p>
        </div>

        <div class="front-block block app">
          <h3><a href="http://smallk.github.io/">SmallK</a></h3>
          <img alt='' src='/_static/images/smallk.png'
          class='avatar avatar-84 photo' height='84' width='84' />

          <p>The <a href="http://smallk.github.io/">SmallK</a> 
            is a high performance software package for low rank matrix 
            approximation via the nonnegative matrix factorization (NMF).
          </p>
        </div>

        <div class="front-block block app">
          <h3><a href="http://researcher.ibm.com/researcher/view_project.php?id=5131">Skylark</a></h3>

          <p>The <a href="http://researcher.ibm.com/researcher/view_project.php?id=5131">Skylark</a> 
            library supplies sketching-based Numerical Linear Algebra (NLA) 
            kernels for general statistical data analysis and optimization 
            applications.  
          </p>
        </div>
      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
