<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

      	<div class="front-block block app">
	  <h3><a href="http://github.com/poulson/Clique">Clique</a></h3>
          <img alt='' src='/_static/images/clique.png'
          class='avatar avatar-84 photo' height='84' width='74' />

	  <p><a href="http://github.com/poulson/Clique">Clique</a> is a
          distributed-memory sparse-direct solver with a focus on memory
          and triangular-solve scalability. It currently supports 
          symmetric and Hermitian linear systems and is currently being merged
          into Elemental.</p>
        </div>

      	<div class="front-block block app">
	  <h3><a href="http://github.com/poulson/PSP">PSP &mdash; Parallel Sweeping Preconditioner</a></h3>
          <img alt='' src='/_static/images/psp.png'
          class='avatar avatar-84 photo' height='84' width='84' />

	  <p><a href="http://github.com/poulson/PSP">PSP</a> is a prototype
             <a href="http://epubs.siam.org/doi/abs/10.1137/120871985">parallel
             sweeping preconditioner</a> for 
             large-scale
             heterogeneous 3D time-harmonic wave equations.
          </p>
        </div>

        <div class="front-block block app">
          <h3><a href="http://github.com/poulson/rt-lps-mri">Real-Time Low-rank Plus Sparse MRI</a></h3>
          <img alt='' src='/_static/images/rt-lps-mri.png'
          class='avatar avatar-84 photo' height='84' width='84' />

          <p><a href="http://github.com/poulson/rt-lps-mri">RT-LPS-MRI</a>
             is a distributed-memory parallelization of a Low-Rank Plus Sparse
             decomposition for dynamically accelerated MRI.
          </p>
        </div>
      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
