<div id="leader">
  <div id="leader-container">
    <div id="feature">

      <!--- Featured item --->
      <div id="products_example">
        <div id="products">
          <div class="slides_container">
	    <div class="slide">
	      <a href="/featured/2012/csf.html"><img src="/_static/images/featured/featured_item_csf.png" width="366" height="282" alt="Cerebrospinal fluid flow"></a>
	      <div class="caption">
		<p>Example 1</p>
	      </div>
	    </div>
	    <div class="slide">
	      <a href="/featured/2011/automated_error_control.html"><img src="/_static/images/featured/featured_item_automated_error_control.png" width="366" height="282" alt="Automated adaptivity and error control"></a>
	      <div class="caption">
		<p>Example 2</p>
	      </div>
	    </div>
	    <div class="slide">
	      <a href="/featured/2011/pdesys.html"><img src="/_static/images/featured/featured_item_pdesys.png" width="366" height="282" alt="Specifying large systems of PDEs with ease"></a>
	      <div class="caption">
		<p>Example 3</p>
	      </div>
	    </div>
          </div>
        </div>
      </div>

      <div id="feature-info">
        <p>Elemental is open-source software for distributed-memory dense
           linear algebra.
        </p>

	<p>Through this web site, you can <a href="/about/">learn more
	    about the project</a> and learn <a href="/download/">how to
	    obtain</a> and <a href="/documentation/">how to use</a> our
	    software. We'd be delighted to <a href="/support/">offer
	    support</a> in case you need it,
	    and <a href="/contributing/">encourage contributions</a>
	    from our users.
        </p>

	<p style="text-align:center;">
	  <a href="/download/">
	    <img style="margin-left:auto; margin-right:auto; margin-top:10px;"
		 src="/_static/download-button-1.2.0.png" alt="Download button" />
	  </a>
	</p>

      </div><!-- #feature-info -->
      <div class="clear-block"></div>
    </div><!-- #feature -->
  </div><!-- #leader-container -->
</div><!-- #leader -->

<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">
	<div id="front-block-1" class="front-block block">

          <p>A workshop on Elemental was held on June 10, 2013 at
             the University of Oregon as part of the <a href="http://ics-conference.org">International Conference on Supercomputing</a>. 
             Presentations from the workshop
             can be found <a href="featured/2013/ics13.html">here (eventually)</a>.
            <br /> <br /> <br /> <br /> <br />
          </p>

          <h3>Who's behind Elemental?</h3>
          <a href="/about/team.html"><img alt='' src='/_static/images/mugshots/jack-poulson.jpeg' class='avatar avatar-84 photo' width='84' /></a>

          <p>TODO
          </p>

          <p><a href="/about/" rel="nofollow">Find out more about
          our project &raquo;</a></p>

        </div><!-- #front-block-1 .front-block .block-->

        <div id="front-block-2" class="front-block block">
          <h3>Recent project news <a href="/_static/news/feed.xml" title="Elemental News RSS feed" rel="alternate nofollow" type="application/rss+xml"><img src="/_static/feed-icon-14x14.gif" alt="RSS"/></a></h3>
	  <!--#include virtual="_static/news/include.html"-->
        </div><!-- #front-block-2 .front-block .block-->

      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
