<HR><FORM ACTION="http://kundenserver.de/cgi-bin/mailinglist.cgi" METHOD="POST" TARGET="_BLANK"><INPUT CHECKED NAME="subscribe_r" TYPE="RADIO" VALUE="subscribe">
				Yes, I want to become a member of the mailing list
				discuss@libelemental.org
				.
				<BR><INPUT NAME="subscribe_r" TYPE="RADIO" VALUE="unsubscribe">
				Please remove me from mailing list
				discuss@libelemental.org
				.
				<BR>

				Enter your e-mail address:
				<BR><INPUT MAXLENGTH="51" NAME="mailaccount_r" SIZE="51" TYPE="TEXT"><BR>
				Please confirm your e-mail address:
				<BR><INPUT MAXLENGTH="51" NAME="mailaccount2_r" SIZE="51" TYPE="TEXT"><BR><INPUT TYPE="SUBMIT" VALUE="Send"><INPUT TYPE="RESET" VALUE="Reset"><HR><INPUT NAME="FBMLNAME" TYPE="HIDDEN" VALUE="discuss@libelemental.org"><INPUT NAME="FBLANG" TYPE="HIDDEN" VALUE="en"><INPUT NAME="FBURLERROR_L" TYPE="HIDDEN" VALUE="http://kundenserver.de/mailinglist/error.en.html"><INPUT NAME="FBURLSUBSCRIBE_L" TYPE="HIDDEN" VALUE="http://kundenserver.de/mailinglist/subscribe.en.html"><INPUT NAME="FBURLUNSUBSCRIBE_L" TYPE="HIDDEN" VALUE="http://kundenserver.de/mailinglist/unsubscribe.en.html"><INPUT NAME="FBURLINVALID_L" TYPE="HIDDEN" VALUE="http://kundenserver.de/mailinglist/invalid.en.html"></FORM>
